<?php
namespace App\Models;
use PDO;
class Leaderboard
{
    private static ?PDO $pdo = null;
    private static function pdo(): PDO { require_once __DIR__ . '/../config/db.php'; return self::$pdo ??= $GLOBALS['pdo']; }
    public static function getPaginated(?int $roomId, ?string $difficulty, int $limit, int $offset): array { $sql = 'SELECT le.id AS entry_id, le.team_id, le.room_id, r.title AS room_title, r.difficulty, t.name AS team_name, le.total_score, le.time_taken_seconds, le.completed_at, RANK() OVER (ORDER BY le.total_score DESC, le.time_taken_seconds ASC) AS global_rank FROM leaderboard_entries le JOIN teams t ON t.id = le.team_id JOIN rooms r ON r.id = le.room_id WHERE 1=1'; $params = []; if ($roomId) { $sql .= ' AND le.room_id = :room_id'; $params[':room_id'] = $roomId; } if ($difficulty) { $sql .= ' AND r.difficulty = :difficulty'; $params[':difficulty'] = $difficulty; } $sql .= ' ORDER BY le.total_score DESC, le.time_taken_seconds ASC LIMIT :limit OFFSET :offset'; $stmt = self::pdo()->prepare($sql); foreach ($params as $key => $value) $stmt->bindValue($key, $value, is_int($value) ? PDO::PARAM_INT : PDO::PARAM_STR); $stmt->bindValue(':limit', $limit, PDO::PARAM_INT); $stmt->bindValue(':offset', $offset, PDO::PARAM_INT); $stmt->execute(); return $stmt->fetchAll(PDO::FETCH_ASSOC); }
    public static function countTotal(?int $roomId, ?string $difficulty): int { $sql = 'SELECT COUNT(*) FROM leaderboard_entries le JOIN rooms r ON r.id = le.room_id WHERE 1=1'; $params = []; if ($roomId) { $sql .= ' AND le.room_id = :room_id'; $params[':room_id'] = $roomId; } if ($difficulty) { $sql .= ' AND r.difficulty = :difficulty'; $params[':difficulty'] = $difficulty; } $stmt = self::pdo()->prepare($sql); $stmt->execute($params); return (int)$stmt->fetchColumn(); }
    public static function getUserBest(int $userId): ?array { $stmt = self::pdo()->prepare('SELECT le.*, t.name AS team_name, r.title AS room_title FROM leaderboard_entries le JOIN teams t ON t.id = le.team_id JOIN team_members tm ON tm.team_id = t.id JOIN rooms r ON r.id = le.room_id WHERE tm.user_id = :user_id ORDER BY le.total_score DESC, le.time_taken_seconds ASC LIMIT 1'); $stmt->execute([':user_id' => $userId]); $row = $stmt->fetch(PDO::FETCH_ASSOC); return $row ?: null; }
    public static function getTopForRoom(int $roomId, int $limit = 10): array { $stmt = self::pdo()->prepare('SELECT le.*, t.name AS team_name FROM leaderboard_entries le JOIN teams t ON t.id = le.team_id WHERE le.room_id = :room_id ORDER BY le.total_score DESC, le.time_taken_seconds ASC LIMIT :limit'); $stmt->bindValue(':room_id', $roomId, PDO::PARAM_INT); $stmt->bindValue(':limit', $limit, PDO::PARAM_INT); $stmt->execute(); return $stmt->fetchAll(PDO::FETCH_ASSOC); }
}
